name: Upload to CurseForge

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip
        run: |
          mkdir TwitchDropsWatcher
          cp *.lua *.toc TwitchDropsWatcher/
          cp -r images libs icons TwitchDropsWatcher/
          zip -r TwitchDropsWatcher.zip TwitchDropsWatcher

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: "${{ secrets.TWITCHDROPSWATCHER }}"
          project_id: "1310016"
          game_endpoint: "wow"
          file_path: "TwitchDropsWatcher.zip"
          game_versions: "12.0.5"
          release_type: "release"
          display_name: "TwitchDropsWatcher - ${{ github.event.head_commit.timestamp }}"
          changelog: "${{ github.event.head_commit.message }}"
          changelog_type: "markdown"